  # The <title> of the index page.
  title = "Tailon file viewer"

  # The root of the web application.
  relative-root = "/"

  # The addresses to listen on. Can be an address:port combination or an unix socket.
  listen-addr = ["127.0.0.1:9002"]

  # Allow download of know files (only those matched by a filespec).
  allow-download = true

  # Commands that will appear in the UI.
  allow-commands = ["tail", "grep", "sed", "awk"]

  # File, glob and dir filespecs are similar in principle to their
  # command-line counterparts.

  # how many lines of code are displayed at once in the GUI terminal
  # 0 means all of them
  lines-of-history = 3001
 
  # how many lines will tail start with. +1 means all of tehm, aka, start at the first line
  lines-to-tail = 3001

  [files]
    file = "testdata/ex1/var/log/4.log"
    #filei2 = "alias=test,group=test_group,log.log"
 
  [commands]

    [commands.tail]
    action = ["tail", "-n", "$lines", "-F", "$path"]
#    action = ["tail", "-n", "+1", "-F", "$path"]
    [commands.grep]
    stdin = "tail"
    action = ["grep", "--text", "--line-buffered", "--color=never", "-i", "-e", "$script"]
    default = ".*"

    [commands.sed]
    stdin = "tail"
    action = ["sed", "-u", "-e", "$script"]
    default = "s/.*/&/"

    [commands.awk]
    stdin = "tail"
    action = ["awk", "--sandbox", "$script"]
    default = "{print $0; fflush()}"

